name: Keep Workflow Running

# This triggers the workflow automatically every 15 minutes
on:
  schedule:
    - cron: '*/1 * * * *'  # Every 15 minutes
  workflow_dispatch:         # Manual run option

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Time
        run: echo "This workflow ran at $(date)"
        
      - name: Optional - Ping Your Server
        run: curl -s https://github.com/gamernestt/Test/actions/runs/14401151791/job/40387014707/ping

      - name: Optional - Run a Script
        run: |
          echo "Running custom code..."
          # Insert your script logic here
